name: 'Chromatic DSPOT'

on:
  push:
    branches:
      - main
      - staging
      - dev
  pull_request:
        branches: ['main', 'staging', 'dev']
        types: [opened, synchronize]
  workflow_dispatch:

env:
  HUSKY: 0
  NX_ISOLATE_PLUGINS: false

jobs:
  chromatic:
    name: Run Chromatic
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.ref }}

      - name: Install PNPM
        uses: pnpm/action-setup@v3
        with:
          version: 10
          run_install: false

      - name: Install Dependencies
        run: pnpm install

      - name: Build packages
        run: pnpm build

      - name: Run Chromatic
        uses: chromaui/action@latest
        with:
          projectToken: ${{ secrets.CHROMATIC_DSPOT_PROJECT_TOKEN }}
          exitZeroOnChanges: true # fail on changes
          onlyChanged: true # enable TurboSnap https://www.chromatic.com/docs/turbosnap